[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#B7A3E3"
backgroundColor = "#F9F8F6"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "DIN"
base = "light"
