[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#B7A3E3"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F9F8F6"
textColor = "#262730"
font = "DIN"
base = "light"
