[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3C4F91"        # accent color (optional)
backgroundColor = "#FFFFFF"     # main background (optional)
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "DIN"